import './globals.css'
import type { Metadata } from 'next'
import { Bricolage_Grotesque as BricolageGrotesque } from 'next/font/google'

const bricolageGrotesque = BricolageGrotesque({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Money App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bricolageGrotesque.className}>{children}</body>
    </html>
  )
}
